server:
  port: 8899
  contextPath: /userauth

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: password
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: false
      hibernate:
        ddl-auto: create

security:
  user:
    password: password

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/