server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "file://C:/Users/ace/IdeaProjects/sace/config"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8600/EurekaServer/eureka
